from __future__ import annotations

from typing import List, NotRequired, TypedDict


class RiskEventConfig(TypedDict):
    event_key: str
    display_title: str
    category: str
    region_tag: str
    pair_tag: str
    impact_weight: float
    query_keywords: List[str]
    event_slug_allowlist: List[str]
    market_slug_allowlist: List[str]
    active: bool
    must_contain_any: NotRequired[List[str]]
    must_contain_all: NotRequired[List[str]]
    must_contain_any_group: NotRequired[List[List[str]]]
    exclude_keywords: NotRequired[List[str]]


class OngoingChaosClusterConfig(TypedDict):
    cluster_key: str
    display_title: str
    category: str
    region_tag: str
    pair_tag: str
    max_points: float
    intensity_multiplier: float
    query_keywords: List[str]
    event_slug_allowlist: List[str]
    market_slug_allowlist: List[str]
    active: bool
    must_contain_any: NotRequired[List[str]]
    must_contain_all: NotRequired[List[str]]
    must_contain_any_group: NotRequired[List[List[str]]]
    exclude_keywords: NotRequired[List[str]]


class FocusedConflictWatchConfig(TypedDict):
    watch_key: str
    country_codes: List[str]
    query_keywords: List[str]
    active: bool


RISK_CATEGORIES = {
    "military_conflict": "军事冲突",
    "nuclear_escalation": "核升级",
    "political_instability": "政治失稳",
    "economic_crisis": "经济危机",
    "public_health": "公共卫生",
}

RISK_INDEX_CONFIG = {
    "methodology_version": "wci_v2",
    "liquidity_floor": 0.60,
    "liquidity_ceiling": 1.20,
    "liquidity_ref_usd": 1_000_000,
    "ema_alpha": 0.70,
    "max_events": 25,
    "pressure_curve_scale": 1.35,
    "escalation_score_max": 30.0,
    "ongoing_score_max": 60.0,
    "contagion_bonus_max": 10.0,
    "cluster_min_probability": 0.08,
    "polymarket_candidate_limit": 400,
    "polymarket_fetch_page_size": 200,
    "polymarket_fetch_max_pages": 8,
    "polymarket_supplemental_max_pages": 6,
    "news_explainer_delta_threshold": 0.05,
    "monitored_markets_limit": 24,
    "dynamic_conflict_limit": 36,
    "dynamic_conflict_base_impact": 0.55,
    "conditional_outcome_weight_multiplier": 0.35,
    "dynamic_conflict_country_weights": {
        "USA": 1.00,
        "CHN": 1.00,
        "RUS": 0.75,
        "IND": 0.75,
        "default": 0.35,
    },
    "dynamic_conflict_conditional_keywords": [
        "survive",
        "regime",
        "collapse",
        "fall",
        "removed",
        "overthrown",
        "after",
        "following",
    ],
    "dynamic_conflict_action_keywords": [
        "war",
        "strike",
        "attack",
        "invade",
        "invasion",
        "military clash",
        "ground operation",
        "forces enter",
        "article 5",
        "missile",
        "bomb",
        "blockade",
        "conflict",
        "operation",
    ],
    "dynamic_conflict_exclude_keywords": [
        "ceasefire",
        "conflict ends",
        "returns to normal",
        "visit",
        "say",
        "post",
        "meet",
        "meeting",
        "diplomatic",
        "talk",
        "tweet",
        "truth social",
        "speech",
        "recognizes",
        "recognizes sovereignty",
        "sovereignty",
        "security guarantee",
        "guarantee",
        "press briefing",
    ],
    "dynamic_conflict_country_aliases": {
        "USA": ["usa", "u.s.", "u.s", "american", "united states", "america"],
        "CHN": ["china", "chinese", "prc"],
        "RUS": ["russia", "russian"],
        "IND": ["india", "indian"],
        "JPN": ["japan", "japanese"],
        "CUB": ["cuba", "cuban"],
        "MEX": ["mexico", "mexican"],
        "ISR": ["israel", "israeli"],
        "TUR": ["turkey", "turkish"],
        "IRN": ["iran", "iranian"],
        "UKR": ["ukraine", "ukrainian"],
        "PAK": ["pakistan", "pakistani"],
        "PRK": ["north korea", "dprk", "north korean"],
        "ROK": ["south korea", "south korean", "korea"],
        "COL": ["colombia", "colombian"],
        "TWN": ["taiwan", "taiwanese"],
        "SAU": ["saudi", "saudi arabia"],
        "NATO": ["nato"],
    },
    "polymarket_allowed_tag_slugs": [
        "geopolitics",
        "conflict",
        "military-strikes",
        "diplomacy-ceasefire",
        "economy",
        "economic-policy",
        "finance",
        "energy",
        "oil",
        "commodities",
        "interest-rates",
        "global-rates",
        "sovereign-debt",
        "inflation",
        "recession",
        "tariffs",
        "trade-war",
        "banking",
    ],
    "polymarket_allowed_text_keywords": [
        "war",
        "strike",
        "attack",
        "ceasefire",
        "invade",
        "military clash",
        "article 5",
        "nuclear",
        "iran",
        "israel",
        "turkey",
        "taiwan",
        "china",
        "japan",
        "north korea",
        "south korea",
        "nato",
        "ukraine",
        "russia",
        "hormuz",
        "red sea",
        "oil",
        "treasury",
        "debt default",
        "sovereign default",
        "banking crisis",
        "recession",
        "interest rate",
        "sanctions",
    ],
    "polymarket_excluded_tag_slugs": [
        "sports",
        "soccer",
        "nba",
        "nfl",
        "mlb",
        "nhl",
        "tennis",
        "golf",
        "entertainment",
        "movies",
        "television",
        "music",
        "crypto",
        "memecoins",
    ],
}

FOCUSED_CONFLICT_WATCHLIST_V1: List[FocusedConflictWatchConfig] = [
    {
        "watch_key": "ISR_TUR",
        "country_codes": ["ISR", "TUR"],
        "query_keywords": ["israel turkey", "israel x turkey", "turkey israel", "military clash"],
        "active": True,
    },
    {
        "watch_key": "CHN_JPN",
        "country_codes": ["CHN", "JPN"],
        "query_keywords": ["china japan", "china x japan", "japan china", "military clash"],
        "active": True,
    },
    {
        "watch_key": "USA_CUB",
        "country_codes": ["USA", "CUB"],
        "query_keywords": ["us cuba", "usa cuba", "u.s. cuba", "strike cuba", "invade cuba"],
        "active": True,
    },
    {
        "watch_key": "USA_MEX",
        "country_codes": ["USA", "MEX"],
        "query_keywords": ["us mexico", "usa mexico", "u.s. mexico", "strike mexico", "ground operation mexico"],
        "active": True,
    },
    {
        "watch_key": "USA_LATAM",
        "country_codes": ["USA", "COL", "MEX", "CUB"],
        "query_keywords": ["latin america", "latin american country", "anti-cartel ground operation", "colombia"],
        "active": True,
    },
    {
        "watch_key": "RUS_NATO",
        "country_codes": ["RUS", "NATO"],
        "query_keywords": ["russia nato", "nato article 5", "article 5", "nato clash"],
        "active": True,
    },
    {
        "watch_key": "PRK_ROK",
        "country_codes": ["PRK", "ROK"],
        "query_keywords": ["north korea south korea", "korean war", "north korea attack south korea"],
        "active": True,
    },
    {
        "watch_key": "CHN_TWN",
        "country_codes": ["CHN", "TWN"],
        "query_keywords": ["china taiwan", "taiwan blockade", "taiwan invasion"],
        "active": True,
    },
]

EVENT_BASKET_V1: List[RiskEventConfig] = [
    {
        "event_key": "us_iran_direct_strike",
        "display_title": "美伊直接军事冲突",
        "category": "military_conflict",
        "region_tag": "middle_east",
        "pair_tag": "USA_IRN",
        "impact_weight": 0.90,
        "query_keywords": [
            "U.S. Iran strike",
            "US Iran war",
            "U.S. attack Iran",
            "usa iran strike",
            "usa attack iran",
            "iran strike",
            "iran war",
        ],
        "event_slug_allowlist": ["iran", "us-iran", "strike-iran"],
        "market_slug_allowlist": ["iran", "strike-iran", "attack-iran"],
        "must_contain_all": ["iran"],
        "must_contain_any_group": [["usa", "iran"], ["american", "iran"], ["us force", "iran"]],
        "must_contain_any": ["strike", "attack", "war", "forces enter"],
        "exclude_keywords": ["nuclear deal", "conflict ends", "ceasefire", "israel", "saudi"],
        "active": True,
    },
    {
        "event_key": "israel_iran_direct_war",
        "display_title": "以伊直接战争升级",
        "category": "military_conflict",
        "region_tag": "middle_east",
        "pair_tag": "ISR_IRN",
        "impact_weight": 0.88,
        "query_keywords": [
            "Israel Iran war",
            "Israel strikes Iran",
            "Iran Israel conflict",
            "israel attack iran",
            "iran israel war",
            "israel iran strike",
        ],
        "event_slug_allowlist": ["israel", "iran", "israel-iran"],
        "market_slug_allowlist": ["israel", "iran", "strike-iran"],
        "must_contain_all": ["iran", "israel"],
        "must_contain_any": ["strike", "attack", "war", "conflict"],
        "exclude_keywords": ["nuclear deal", "conflict ends", "ceasefire"],
        "active": True,
    },
    {
        "event_key": "hormuz_closure",
        "display_title": "霍尔木兹海峡封锁",
        "category": "economic_crisis",
        "region_tag": "middle_east",
        "pair_tag": "GULF_OIL",
        "impact_weight": 0.72,
        "query_keywords": [
            "Hormuz closure",
            "Strait of Hormuz blocked",
            "Iran Hormuz",
            "hormuz blocked",
            "strait of hormuz",
            "oil shipping gulf",
        ],
        "event_slug_allowlist": ["hormuz", "strait-of-hormuz"],
        "market_slug_allowlist": ["hormuz", "strait-of-hormuz"],
        "must_contain_any_group": [["hormuz", "block"], ["hormuz", "close"], ["strait of hormuz", "shut"]],
        "must_contain_any": ["block", "blocked", "close", "closure", "shut"],
        "exclude_keywords": ["returns to normal", "traffic normal", "normal"],
        "active": True,
    },
    {
        "event_key": "saudi_iran_regional_escalation",
        "display_title": "海湾地区冲突外溢",
        "category": "military_conflict",
        "region_tag": "middle_east",
        "pair_tag": "GULF_REGIONAL",
        "impact_weight": 0.68,
        "query_keywords": [
            "Saudi Iran conflict",
            "Gulf conflict escalation",
            "Middle East regional war",
            "middle east war",
            "gulf war",
            "regional war middle east",
        ],
        "event_slug_allowlist": ["saudi-iran", "gulf-war", "regional-war"],
        "market_slug_allowlist": ["saudi-iran", "gulf-war"],
        "must_contain_any_group": [["saudi", "iran"], ["gulf state", "iran"]],
        "must_contain_any": ["strike", "attack", "war", "conflict", "military action"],
        "exclude_keywords": ["crude oil hit", "oil hit", "conflict ends", "ceasefire", "visit", "meeting", "diplomatic"],
        "active": True,
    },
    {
        "event_key": "china_taiwan_blockade",
        "display_title": "台海封锁升级",
        "category": "military_conflict",
        "region_tag": "east_asia",
        "pair_tag": "CHN_TWN",
        "impact_weight": 1.00,
        "query_keywords": ["Taiwan blockade", "China Taiwan blockade", "Taiwan crisis", "taiwan crisis", "china taiwan"],
        "event_slug_allowlist": ["taiwan", "china-taiwan"],
        "market_slug_allowlist": ["taiwan", "china-taiwan"],
        "active": True,
    },
    {
        "event_key": "china_taiwan_invasion",
        "display_title": "台海热战爆发",
        "category": "military_conflict",
        "region_tag": "east_asia",
        "pair_tag": "CHN_TWN",
        "impact_weight": 1.00,
        "query_keywords": [
            "China invades Taiwan",
            "Taiwan invasion",
            "PRC Taiwan war",
            "china taiwan invasion",
            "invade taiwan",
        ],
        "event_slug_allowlist": ["invade-taiwan", "taiwan", "china-taiwan"],
        "market_slug_allowlist": ["invade-taiwan", "taiwan"],
        "active": True,
    },
    {
        "event_key": "us_china_direct_clash",
        "display_title": "中美直接军事摩擦",
        "category": "military_conflict",
        "region_tag": "east_asia",
        "pair_tag": "USA_CHN",
        "impact_weight": 0.95,
        "query_keywords": [
            "U.S. China war",
            "US China military clash",
            "South China Sea war",
            "usa china war",
            "south china sea clash",
        ],
        "event_slug_allowlist": ["usa-china", "south-china-sea", "china-war"],
        "market_slug_allowlist": ["usa-china", "south-china-sea"],
        "must_contain_any_group": [["usa", "china"], ["american", "china"], ["south china sea"]],
        "must_contain_any": ["war", "clash", "conflict", "attack", "military"],
        "exclude_keywords": ["taiwan", "visit", "trade", "tariff", "deal"],
        "active": True,
    },
    {
        "event_key": "north_korea_attack_south",
        "display_title": "朝鲜半岛军事冲突",
        "category": "military_conflict",
        "region_tag": "korean_peninsula",
        "pair_tag": "PRK_ROK",
        "impact_weight": 0.92,
        "query_keywords": [
            "North Korea attack South Korea",
            "Korean war",
            "North Korea conflict",
            "north korea south korea",
            "korea conflict",
        ],
        "event_slug_allowlist": ["north-korea", "korea-war", "north-korea-attack"],
        "market_slug_allowlist": ["north-korea", "korea-war", "north-korea-attack"],
        "must_contain_all": ["north korea"],
        "must_contain_any": ["south korea", "attack", "war", "missile", "conflict"],
        "active": True,
    },
    {
        "event_key": "north_korea_attack_us_assets",
        "display_title": "朝鲜攻击美军或盟军目标",
        "category": "military_conflict",
        "region_tag": "korean_peninsula",
        "pair_tag": "PRK_USA",
        "impact_weight": 0.95,
        "query_keywords": [
            "North Korea attacks U.S.",
            "North Korea missile U.S. base",
            "PRK US conflict",
            "north korea usa",
            "north korea missile usa",
        ],
        "event_slug_allowlist": ["north-korea-missile", "prk-us", "north-korea-attack-us"],
        "market_slug_allowlist": ["north-korea-missile", "prk-us", "north-korea-attack-us"],
        "must_contain_all": ["north korea"],
        "must_contain_any_group": [["north korea", "usa"], ["north korea", "american"], ["north korea", "guam"], ["north korea", "us base"]],
        "must_contain_any": ["attack", "missile", "strike", "base", "asset", "troops"],
        "exclude_keywords": ["visit", "summit", "south korea", "invade south korea"],
        "active": True,
    },
    {
        "event_key": "north_korea_nuclear_test_or_use",
        "display_title": "朝鲜核升级",
        "category": "nuclear_escalation",
        "region_tag": "korean_peninsula",
        "pair_tag": "PRK_NUCLEAR",
        "impact_weight": 0.98,
        "query_keywords": [
            "North Korea nuclear test",
            "North Korea nuclear use",
            "PRK nuclear crisis",
            "north korea nuclear",
            "nuclear test korea",
        ],
        "event_slug_allowlist": ["north-korea", "nuclear"],
        "market_slug_allowlist": ["north-korea", "nuclear"],
        "must_contain_all": ["north korea", "nuclear"],
        "exclude_keywords": ["nuclear deal"],
        "active": True,
    },
    {
        "event_key": "russia_nato_direct_clash",
        "display_title": "俄与北约直接冲突",
        "category": "military_conflict",
        "region_tag": "europe",
        "pair_tag": "RUS_NATO",
        "impact_weight": 1.00,
        "query_keywords": [
            "Russia NATO war",
            "Russia NATO direct conflict",
            "Article 5 conflict",
            "russia nato",
            "article 5",
        ],
        "event_slug_allowlist": ["russia-nato", "article-5", "russia-attack-nato", "nato-russia"],
        "market_slug_allowlist": ["russia-nato", "article-5", "russia-attack-nato", "nato-russia"],
        "must_contain_any_group": [["russia", "nato"], ["article 5", "russia"], ["moscow", "nato"]],
        "must_contain_any": ["war", "clash", "attack", "strike", "article 5", "conflict"],
        "exclude_keywords": ["security guarantee", "recognizes sovereignty", "ceasefire", "visit", "meeting", "guarantee"],
        "active": True,
    },
    {
        "event_key": "nuclear_weapon_use_anywhere",
        "display_title": "核武器实际使用",
        "category": "nuclear_escalation",
        "region_tag": "global",
        "pair_tag": "GLOBAL_NUCLEAR",
        "impact_weight": 1.00,
        "query_keywords": [
            "nuclear weapon used",
            "nuclear strike",
            "tactical nuclear weapon",
            "nuclear use",
            "nuclear detonation",
        ],
        "event_slug_allowlist": ["nuclear-weapon", "nuclear-strike", "tactical-nuclear"],
        "market_slug_allowlist": ["nuclear-weapon", "nuclear-strike", "tactical-nuclear"],
        "must_contain_any": ["nuclear weapon", "nuclear strike", "tactical nuclear", "atomic weapon"],
        "exclude_keywords": ["nuclear deal"],
        "active": True,
    },
    {
        "event_key": "serbia_kosovo_escalation",
        "display_title": "塞尔维亚-科索沃冲突升级",
        "category": "military_conflict",
        "region_tag": "balkans",
        "pair_tag": "SRB_KOS",
        "impact_weight": 0.62,
        "query_keywords": [
            "Serbia Kosovo conflict",
            "Serbia Kosovo war",
            "Balkans escalation",
            "serbia kosovo",
            "kosovo conflict",
        ],
        "event_slug_allowlist": ["serbia-kosovo", "kosovo-conflict"],
        "market_slug_allowlist": ["serbia-kosovo", "kosovo-conflict"],
        "must_contain_any_group": [["serbia", "kosovo"]],
        "must_contain_any": ["conflict", "war", "border", "clash", "troops"],
        "exclude_keywords": ["ukraine", "russia", "sovereignty", "recognizes", "visit", "meeting"],
        "active": True,
    },
    {
        "event_key": "balkan_regional_instability",
        "display_title": "巴尔干地区安全外溢",
        "category": "political_instability",
        "region_tag": "balkans",
        "pair_tag": "BALKANS_REGIONAL",
        "impact_weight": 0.42,
        "query_keywords": [
            "Balkans instability",
            "Serbia unrest",
            "Bosnia crisis",
            "Kosovo unrest",
            "balkans crisis",
        ],
        "event_slug_allowlist": ["balkans-crisis", "serbia-unrest", "bosnia-crisis", "kosovo-unrest"],
        "market_slug_allowlist": ["balkans-crisis", "serbia-unrest", "bosnia-crisis", "kosovo-unrest"],
        "must_contain_any": ["balkans crisis", "serbia unrest", "bosnia crisis", "kosovo unrest"],
        "active": True,
    },
    {
        "event_key": "us_debt_default",
        "display_title": "美国国债违约",
        "category": "economic_crisis",
        "region_tag": "north_america",
        "pair_tag": "USA_DEBT",
        "impact_weight": 0.85,
        "query_keywords": [
            "U.S. debt default",
            "US Treasury default",
            "U.S. misses debt payment",
            "us default",
            "treasury default",
            "debt ceiling default",
        ],
        "event_slug_allowlist": ["treasury-default", "debt-default", "debt-ceiling"],
        "market_slug_allowlist": ["treasury-default", "debt-default", "debt-ceiling"],
        "must_contain_any": ["treasury default", "debt default", "debt ceiling default", "us default"],
        "exclude_keywords": ["atp", "paris", "vs", "simakin"],
        "active": True,
    },
    {
        "event_key": "major_sovereign_default",
        "display_title": "主要主权国家违约",
        "category": "economic_crisis",
        "region_tag": "global",
        "pair_tag": "SOV_DEFAULT",
        "impact_weight": 0.58,
        "query_keywords": [
            "sovereign default",
            "major country default",
            "government debt crisis",
            "country default",
            "government default",
        ],
        "event_slug_allowlist": ["sovereign-default", "government-default"],
        "market_slug_allowlist": ["sovereign-default", "government-default"],
        "must_contain_any": ["sovereign default", "government default", "country default"],
        "active": True,
    },
    {
        "event_key": "global_banking_crisis",
        "display_title": "全球银行业危机",
        "category": "economic_crisis",
        "region_tag": "global",
        "pair_tag": "GLOBAL_BANKING",
        "impact_weight": 0.65,
        "query_keywords": [
            "banking crisis",
            "global bank crisis",
            "financial system crisis",
            "bank crisis",
            "financial crisis",
        ],
        "event_slug_allowlist": ["banking-crisis", "financial-crisis"],
        "market_slug_allowlist": ["banking-crisis", "financial-crisis"],
        "must_contain_any": ["bank crisis", "banking crisis", "financial crisis"],
        "active": True,
    },
    {
        "event_key": "global_recession",
        "display_title": "全球衰退风险",
        "category": "economic_crisis",
        "region_tag": "global",
        "pair_tag": "GLOBAL_RECESSION",
        "impact_weight": 0.48,
        "query_keywords": ["global recession", "world recession", "hard landing", "recession", "landing"],
        "event_slug_allowlist": ["recession", "hard-landing"],
        "market_slug_allowlist": ["recession", "hard-landing"],
        "must_contain_any": ["recession", "hard landing"],
        "active": True,
    },
    {
        "event_key": "oil_price_spike_extreme",
        "display_title": "原油极端飙升冲击",
        "category": "economic_crisis",
        "region_tag": "global",
        "pair_tag": "GLOBAL_OIL",
        "impact_weight": 0.46,
        "query_keywords": ["oil above 120", "oil shock", "crude oil spike", "oil spike", "crude oil"],
        "event_slug_allowlist": ["crude-oil", "oil-hit", "oil-spike"],
        "market_slug_allowlist": ["crude-oil", "oil-hit", "oil-spike"],
        "must_contain_any": ["crude oil", "oil spike", "oil hit"],
        "active": True,
    },
    {
        "event_key": "us_constitutional_crisis",
        "display_title": "美国宪政危机",
        "category": "political_instability",
        "region_tag": "north_america",
        "pair_tag": "USA_INTERNAL",
        "impact_weight": 0.45,
        "query_keywords": [
            "U.S. constitutional crisis",
            "US election crisis",
            "US internal unrest",
            "usa election crisis",
            "constitutional crisis usa",
        ],
        "event_slug_allowlist": ["constitutional-crisis", "election-crisis", "internal-unrest"],
        "market_slug_allowlist": ["constitutional-crisis", "election-crisis", "internal-unrest"],
        "must_contain_any": ["constitutional crisis", "election crisis", "internal unrest", "civil unrest"],
        "active": True,
    },
    {
        "event_key": "china_internal_instability",
        "display_title": "中国重大内部不稳定事件",
        "category": "political_instability",
        "region_tag": "east_asia",
        "pair_tag": "CHN_INTERNAL",
        "impact_weight": 0.44,
        "query_keywords": [
            "China political instability",
            "China internal unrest",
            "China major crisis",
            "china unrest",
            "china crisis",
        ],
        "event_slug_allowlist": ["china-unrest", "china-crisis", "china-protest"],
        "market_slug_allowlist": ["china-unrest", "china-crisis", "china-protest"],
        "must_contain_all": ["china"],
        "must_contain_any": ["unrest", "crisis", "protest", "internal"],
        "active": True,
    },
    {
        "event_key": "iran_regime_instability",
        "display_title": "伊朗政局剧烈失稳",
        "category": "political_instability",
        "region_tag": "middle_east",
        "pair_tag": "IRN_INTERNAL",
        "impact_weight": 0.43,
        "query_keywords": [
            "Iran regime collapse",
            "Iran unrest",
            "Iran political crisis",
            "iran regime",
            "iran collapse",
        ],
        "event_slug_allowlist": ["iran", "regime", "unrest"],
        "market_slug_allowlist": ["iran", "regime", "unrest"],
        "must_contain_all": ["iran"],
        "must_contain_any": ["regime", "collapse", "unrest", "protest", "supreme leader"],
        "exclude_keywords": ["forces enter", "strike", "attack", "nuclear deal"],
        "active": True,
    },
    {
        "event_key": "who_pheic_or_global_outbreak",
        "display_title": "全球重大疫情暴发",
        "category": "public_health",
        "region_tag": "global",
        "pair_tag": "GLOBAL_PANDEMIC",
        "impact_weight": 0.72,
        "query_keywords": [
            "pandemic declared",
            "global outbreak",
            "WHO emergency outbreak",
            "pandemic",
            "who emergency",
            "global health emergency",
        ],
        "event_slug_allowlist": ["pandemic-declared", "global-outbreak", "health-emergency", "who-emergency"],
        "market_slug_allowlist": ["pandemic-declared", "global-outbreak", "health-emergency", "who-emergency"],
        "must_contain_any_group": [["who", "emergency"], ["pandemic", "declared"], ["global", "outbreak"], ["health", "emergency"]],
        "must_contain_any": ["outbreak", "emergency", "declared"],
        "exclude_keywords": ["whoop", "ipo", "powell", "press conference", "say"],
        "active": True,
    },
    {
        "event_key": "avian_flu_human_spread",
        "display_title": "高致病性流感人际传播",
        "category": "public_health",
        "region_tag": "global",
        "pair_tag": "AVIAN_FLU",
        "impact_weight": 0.62,
        "query_keywords": [
            "bird flu human transmission",
            "H5N1 human spread",
            "avian flu pandemic",
            "avian flu",
            "h5n1",
            "bird flu",
        ],
        "event_slug_allowlist": ["avian", "bird-flu", "h5n1"],
        "market_slug_allowlist": ["avian", "bird-flu", "h5n1"],
        "must_contain_any_group": [["avian flu", "human"], ["bird flu", "human"], ["h5n1", "human"]],
        "must_contain_any": ["avian flu", "bird flu", "h5n1", "transmission", "spread"],
        "exclude_keywords": ["say", "press conference"],
        "active": True,
    },
]


ONGOING_CHAOS_CLUSTERS_V1: List[OngoingChaosClusterConfig] = [
    {
        "cluster_key": "ru_ua_war",
        "display_title": "俄乌战争持续",
        "category": "military_conflict",
        "region_tag": "europe",
        "pair_tag": "RUS_UKR_BASE",
        "max_points": 18.0,
        "intensity_multiplier": 1.00,
        "query_keywords": [
            "russia ukraine ceasefire",
            "ukraine peace deal",
            "russia ukraine war ends",
            "ukraine armistice",
        ],
        "event_slug_allowlist": ["russia-x-ukraine-ceasefire", "ukraine-peace", "war-ends-ukraine"],
        "market_slug_allowlist": ["russia-x-ukraine-ceasefire", "ukraine-peace", "war-ends-ukraine"],
        "must_contain_any_group": [["russia", "ukraine"], ["ukraine", "ceasefire"]],
        "must_contain_any": ["ceasefire", "peace deal", "war ends", "armistice", "truce"],
        "exclude_keywords": ["gta vi", "eurovision", "parliamentary election", "capture"],
        "active": True,
    },
    {
        "cluster_key": "middle_east_hot_conflict",
        "display_title": "中东热冲突持续",
        "category": "military_conflict",
        "region_tag": "middle_east",
        "pair_tag": "MIDEAST_BASE",
        "max_points": 16.0,
        "intensity_multiplier": 1.00,
        "query_keywords": [
            "us iran ceasefire",
            "israel iran ceasefire",
            "middle east ceasefire",
            "iran conflict ends",
        ],
        "event_slug_allowlist": ["iran-ceasefire", "middle-east-ceasefire", "israel-iran-ceasefire"],
        "market_slug_allowlist": ["iran-ceasefire", "middle-east-ceasefire", "israel-iran-ceasefire"],
        "must_contain_any_group": [["iran", "ceasefire"], ["middle east", "ceasefire"], ["israel", "iran"]],
        "must_contain_any": ["ceasefire", "conflict ends", "truce", "peace deal"],
        "exclude_keywords": ["nuclear deal", "returns to normal"],
        "active": True,
    },
    {
        "cluster_key": "hormuz_shipping_disruption",
        "display_title": "霍尔木兹航运扰动持续",
        "category": "economic_crisis",
        "region_tag": "middle_east",
        "pair_tag": "HORMUZ_BASE",
        "max_points": 10.0,
        "intensity_multiplier": 0.90,
        "query_keywords": [
            "hormuz returns to normal",
            "strait of hormuz traffic normal",
            "hormuz shipping normal",
        ],
        "event_slug_allowlist": ["hormuz-traffic-returns-to-normal", "strait-of-hormuz-traffic-returns-to-normal"],
        "market_slug_allowlist": ["hormuz-traffic-returns-to-normal", "strait-of-hormuz-traffic-returns-to-normal"],
        "must_contain_any_group": [["hormuz", "normal"], ["strait of hormuz", "traffic"]],
        "must_contain_any": ["returns to normal", "traffic", "normal", "shipping"],
        "exclude_keywords": ["warship", "escort"],
        "active": True,
    },
]
